# Generated by Django 6.1 on 2026-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='field',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
